ezpass_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /opt/airflow/config/gcp-key.json
      project: "{{ env_var('GCS_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET', 'ezpass_data') }}"
      location: US
      priority: interactive
      maximum_bytes_billed: 1000000000
      timeout_seconds: 300
      job_retry_deadline_seconds: 300
      job_retries: 1