steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-node@v4
    with:
      node-version: lts/*

  - name: Install dependencies
    run: npm install
    working-directory: frontend

  - name: Install Playwright Browsers
    run: npx playwright install --with-deps
    working-directory: frontend

  - name: Start frontend server
    run: npm run start &
    working-directory: frontend

  - name: Wait for server to be ready
    run: npx wait-on http://localhost:3000
    working-directory: frontend

  - name: Run Playwright tests
    run: npx playwright test
    working-directory: frontend

  - uses: actions/upload-artifact@v4
    if: ${{ !cancelled() }}
    with:
      name: playwright-report
      path: frontend/playwright-report/
      retention-days: 30
